### ISSUE TITLE
ERROR: Unknown function id 0x2E, when extracting the text from the german amiga version of indy 3

### ISSUE THREAD

**Issue by gabberhead** [dwatteau/scummtr#58] opened 2024-06-18 21:38 UTC
with the english amiga version and english ega dos version, there is no problem.

this is the verbose log (in the textfile after that, there are only 665 lines of text):

>scummtr -g indy3 -cwh -A aov -p ./ -ofv indy3_amiga_ega_de.txt
ScummTr 0.5.1 (build 20220227-RELEASE) by Thomas Combeleran

Fixing unexpected size at 0x0 in 01.LFL
Fixing unexpected size at 0x5D7E in 01.LFL
Fixing unexpected size at 0x638D in 01.LFL
Fixing unexpected size at 0x7F62 in 01.LFL
Fixing unexpected size at 0x941C in 01.LFL
Fixing unexpected size at 0xAA03 in 01.LFL
Fixing unexpected size at 0x0 in 02.LFL
Fixing unexpected size at 0x0 in 03.LFL
Fixing unexpected size at 0x3672 in 03.LFL
Fixing unexpected size at 0x3CC8 in 03.LFL
Fixing unexpected size at 0x3F0C in 03.LFL
Fixing unexpected size at 0x0 in 04.LFL
Fixing unexpected size at 0xFA0 in 04.LFL
Fixing unexpected size at 0x0 in 06.LFL
Fixing unexpected size at 0x3C53 in 06.LFL
Fixing unexpected size at 0x40E6 in 06.LFL
Fixing unexpected size at 0x0 in 07.LFL
Fixing unexpected size at 0x0 in 08.LFL
Fixing unexpected size at 0x9B3 in 08.LFL
Fixing unexpected size at 0x9D9 in 08.LFL
Fixing unexpected size at 0xA00 in 08.LFL
Fixing unexpected size at 0xB8B in 08.LFL
Fixing unexpected size at 0xD54 in 08.LFL
Fixing unexpected size at 0xDD7 in 08.LFL
Fixing unexpected size at 0xE5B in 08.LFL
Fixing unexpected size at 0xF5B in 08.LFL
Fixing unexpected size at 0x10B4 in 08.LFL
Fixing unexpected size at 0x12C7 in 08.LFL
Fixing unexpected size at 0x12FB in 08.LFL
Fixing unexpected size at 0x132F in 08.LFL
Fixing unexpected size at 0x1392 in 08.LFL
Fixing unexpected size at 0x13F8 in 08.LFL
Fixing unexpected size at 0x1437 in 08.LFL
Fixing unexpected size at 0x14E8 in 08.LFL
Fixing unexpected size at 0x1546 in 08.LFL
Fixing unexpected size at 0x1AA3 in 08.LFL
Fixing unexpected size at 0x2DD4 in 08.LFL
Fixing unexpected size at 0x94B6 in 08.LFL
Fixing unexpected size at 0xB63E in 08.LFL
Fixing unexpected size at 0xBC4E in 08.LFL
Fixing unexpected size at 0xD485 in 08.LFL
Fixing unexpected size at 0x0 in 09.LFL
Fixing unexpected size at 0x308D in 09.LFL
Fixing unexpected size at 0x0 in 12.LFL
Fixing unexpected size at 0x3838 in 12.LFL
Fixing unexpected size at 0x38C5 in 12.LFL
Fixing unexpected size at 0x3903 in 12.LFL
Fixing unexpected size at 0x3E60 in 12.LFL
Fixing unexpected size at 0x0 in 13.LFL
Fixing unexpected size at 0x3744 in 13.LFL
Fixing unexpected size at 0x5EA4 in 13.LFL
Fixing unexpected size at 0x0 in 14.LFL
Fixing unexpected size at 0x2B39 in 14.LFL
Fixing unexpected size at 0x2D7E in 14.LFL
Fixing unexpected size at 0x339C in 14.LFL
Fixing unexpected size at 0x3D14 in 14.LFL
Fixing unexpected size at 0x42FA in 14.LFL
Fixing unexpected size at 0x4AA3 in 14.LFL
Fixing unexpected size at 0x5695 in 14.LFL
Fixing unexpected size at 0x580F in 14.LFL
Fixing unexpected size at 0x7615 in 14.LFL
Fixing unexpected size at 0x93C1 in 14.LFL
Fixing unexpected size at 0x0 in 15.LFL
Fixing unexpected size at 0x6FD5 in 15.LFL
Fixing unexpected size at 0x7693 in 15.LFL
Fixing unexpected size at 0x79F0 in 15.LFL
Fixing unexpected size at 0x7ADD in 15.LFL
Fixing unexpected size at 0x83CE in 15.LFL
Fixing unexpected size at 0x8823 in 15.LFL
Fixing unexpected size at 0x907A in 15.LFL
Fixing unexpected size at 0xA0CD in 15.LFL
Fixing unexpected size at 0xAF10 in 15.LFL
Fixing unexpected size at 0xC09F in 15.LFL
Fixing unexpected size at 0xC725 in 15.LFL
Fixing unexpected size at 0xE7F0 in 15.LFL
Fixing unexpected size at 0x0 in 16.LFL
Fixing unexpected size at 0x337F in 16.LFL
Fixing unexpected size at 0x0 in 17.LFL
Fixing unexpected size at 0x0 in 18.LFL
Fixing unexpected size at 0x51F1 in 18.LFL
Fixing unexpected size at 0x5336 in 18.LFL
Fixing unexpected size at 0x6836 in 18.LFL
Fixing unexpected size at 0x0 in 19.LFL
Fixing unexpected size at 0x7A9 in 19.LFL
Fixing unexpected size at 0x89D in 19.LFL
Fixing unexpected size at 0xFDD in 19.LFL
Fixing unexpected size at 0x0 in 20.LFL
Fixing unexpected size at 0x3600 in 20.LFL
Fixing unexpected size at 0x3762 in 20.LFL
Fixing unexpected size at 0x3793 in 20.LFL
Fixing unexpected size at 0x3923 in 20.LFL
Fixing unexpected size at 0x3940 in 20.LFL
Fixing unexpected size at 0x3C74 in 20.LFL
Fixing unexpected size at 0x3E3B in 20.LFL
Fixing unexpected size at 0x3F5C in 20.LFL
Fixing unexpected size at 0x3FE0 in 20.LFL
Fixing unexpected size at 0x40A9 in 20.LFL
Fixing unexpected size at 0x41C1 in 20.LFL
Fixing unexpected size at 0x4876 in 20.LFL
Fixing unexpected size at 0x4FCB in 20.LFL
Fixing unexpected size at 0x56DE in 20.LFL
Fixing unexpected size at 0x5DA1 in 20.LFL
Fixing unexpected size at 0x6438 in 20.LFL
Fixing unexpected size at 0x7EF4 in 20.LFL
Fixing unexpected size at 0x0 in 21.LFL
Fixing unexpected size at 0x1C59 in 21.LFL
Fixing unexpected size at 0x1CDB in 21.LFL
Fixing unexpected size at 0x1FEF in 21.LFL
Fixing unexpected size at 0x23AB in 21.LFL
Fixing unexpected size at 0x2400 in 21.LFL
Fixing unexpected size at 0x371E in 21.LFL
Fixing unexpected size at 0x4F5B in 21.LFL
Fixing unexpected size at 0x6C3D in 21.LFL
Fixing unexpected size at 0x6D1A in 21.LFL
Fixing unexpected size at 0x83A3 in 21.LFL
Fixing unexpected size at 0x97E3 in 21.LFL
Fixing unexpected size at 0xB483 in 21.LFL
Fixing unexpected size at 0xCC85 in 21.LFL
Fixing unexpected size at 0x0 in 22.LFL
Fixing unexpected size at 0x2139 in 22.LFL
Fixing unexpected size at 0x218D in 22.LFL
Fixing unexpected size at 0x222F in 22.LFL
Fixing unexpected size at 0x2251 in 22.LFL
Fixing unexpected size at 0x2A91 in 22.LFL
Fixing unexpected size at 0x2B8F in 22.LFL
Fixing unexpected size at 0x2B9B in 22.LFL
ERROR: Unknown function id 0x2E

please fix this, because i would like to decensor the text file of the german version. thanx in advance :)

ps: with scummrp, i can unpack and pack the german amiga version with no problems.

**Comment by dwatteau** [comment] 2024-06-19 12:31
Thanks for reporting this!

I don't own this release and I only work from original copies of the game.

If this release is not too rare in Germany, would it be possible for you to send me a physical copy, either as a small "gift" for my work on ScummVM/ScummTR, or just lend me yours for the time that I work on supporting it?

I could also work on the Enhancements asked for this release on the ScummVM bug tracker

Thanks!

**Comment by gabberhead** [comment] 2024-07-13 00:43
i see, u found the problem and fixed it. will u update scummtr for download also?

**Comment by dwatteau** [comment] 2024-07-13 06:13
@gabberhead Yes, I may need a couple of days more because I'm on vacation, but I will build a new test version for you soon.

Do you run Windows or something else?

**Comment by gabberhead** [comment] 2024-07-13 06:36
No Problem. I am using Windows 10 and 11. Im also on vacation, but on a plane right now to croatia and few seconds before the lift off :)

**Comment by dwatteau** [comment] 2024-07-13 12:42
OK @gabberhead, thank you!

So I've made a new *pre-release* of ScummTR with my fix for the German release of Indy3.

The Windows version is here:
https://github.com/dwatteau/scummtr/releases/download/v0.6.0pre1/scummtr-0.6.0pre1-win32.zip

(Windows may show you a Microsoft Defender SmartScreen warning about the programs; they're safe and can be trusted, it's just that you're one of the very first users of this release, so Windows sees this as a new, unknown program in the wild.)

Could you test it on your Amiga release and report back? I've only tested it on the German DOS release I've bought, but I guess the problem is the same between the Amiga and DOS releases.

For what it's worth, this bug was related to https://bugs.scummvm.org/ticket/1675 and https://bugs.scummvm.org/ticket/2715, i.e. the official German releases of Indy3 had some bogus byte for the ꞵ character

Here were the bogus lines, the first one in script 108 from room 23, the second one in script 71 from room 28:

```
[023:SC#0108]^irgendwo hier im Schlo\255.
[028:SC#0071]Nicht so schnell!  Woher weiß ich, da\255 Sie kein Spion sind?
```

i.e. the ꞵ should have been encoded as `\225`, not `\255` which has a very different, reserved meaning in SCUMM scripts.

And have a nice trip!

**Comment by dwatteau** [comment] 2024-07-13 12:43
Also, there are rumours that an official non-censored German release of Indy3 may have existed, potentially released in Austria or Swiss.

There's someone looking into this in the `#engine-scumm` channel of the ScummVM Discord:
https://discord.com/channels/581224060529148060/1031320481942491186/1260980285793898496

**Comment by dwatteau** [comment] 2024-07-13 12:44
…and now that I have this German release, I'll try to see if I have some time to look into the enhancements you've asked about it on the ScummVM bug tracker, this summer.

Thanks for your report!

**Comment by gabberhead** [comment] 2024-07-13 12:56
Ok. But for me I fixed it myself already. I have used those 2 script files from the english version, translate it into german and put it in the german Release of indy 3. I have done it for the amiga and the DOS ega Version, and for indys comment after the bouncing head in the german VGA Version also. And also I did Some changes in the german Uncut Version of the fmtowns Version. Now there is an Audio track for venice, Audio track for room 45 with hitler and the piano Musik in the zepelin is now also an audiotrack and not the Bad Musik of the fmtowns Version. And also I fixed some Timing issues for the Audio track.

**Comment by gabberhead** [comment] 2024-07-14 06:31
it seems its working, but with warnings. but the exportet textfile is complete:

D:\amiga>scummtr -g indy3 -cwh -A aov -of indy3_amiga.txt
ScummTr 0.6.0 (build 20240713-1136-PRERELEASE-1) by Thomas Combeleran

WARNING: Fixing likely misencoded German Eszett character for Indy3
WARNING: Fixing likely misencoded German Eszett character for Indy3

on the dosega version, i didnt had any problems, only amiga. but on that version which i had, i had this warning. u know perhaps where i can fix that warning in the 08.lfl??

D:\dosega>scummrp -g indy3 -o
ScummRp 0.6.0 (build 20240713-1136-PRERELEASE-1) by Thomas Combeleran

WARNING: Gap at 0x2DD1 in 08.LFL

**Comment by dwatteau** [comment] 2024-07-15 19:17
Hi @gabberhead, I've made a new 0.6.0pre2 release here:
https://github.com/dwatteau/scummtr/releases/download/v0.6.0pre2/scummtr-0.6.0pre2-win32.zip

I realized that the previous version didn't properly decode the following line containing another invalid byte for the 'ꞵ' character:

```
[028:SC#0071]Woher weiß ich, daß SIE kein Spion sind?  Ihr Passierschein!
```

(one of Indy's replies once you're done reproducing the [ScummVM Bug#2715](https://bugs.scummvm.org/ticket/2715) case)

Would you mind trying an export/import again with this new `scummtr.exe`, just to make sure that everything is fine, regarding the bug you've reported here?

Oh, and reporting this issue in ScummTR led me to find and fix a 18-year old bug in ScummVM, so that's cool, thanks :)

**Comment by gabberhead** [comment] 2024-07-16 05:45
tested on the amiga version. with the old one:

[028:SCv3#0071]Woher weiß ich, da\255\032\083\073E kein Spion sind?  Ihr Passierschein!

the pre2 version:

[028:SCv3#0071]Woher weiß ich, daß SIE kein Spion sind?  Ihr Passierschein!

looks ok now. i compared it with the translated german fm towns version.

one question. i am using the traslated german fm towns version as blueprint for the german amiga version. and i copied an paste 600 lines already. i extracted with the older version, but i didnt import anything into the amiga version yet. can i keep the old extracted file, and import it later with the newer one, perhaps also with the final version? because i dont know how long it will take. or must i start from the beginning because of the bug? i think, normaly no, because in the 600 lines, there was no error like this one u posted.

ps. 18 year old bug? better late, then never ;)

**Comment by dwatteau** [comment] 2024-07-16 06:52
OK thank you very much for your test @gabberhead, that's the expected result, cool!

> *one question. i am using the traslated german fm towns version as blueprint for the german amiga version. and i copied an paste 600 lines already. i extracted with the older version, but i didnt import anything into the amiga version yet. can i keep the old extracted file, and import it later with the newer one, perhaps also with the final version? because i dont know how long it will take. or must i start from the beginning because of the bug? i think, normaly no, because in the 600 lines, there was no error like this one u posted.*

If the (fan-made, I guess?) German FM-Towns was extracted without any error, there shouldn't be any problem continuing with this file (I guess they didn't try to replicate the original `ß` bugs :p).

Just watch out for the possible script order differences between the FM-TOWNS and DOS/Amiga releases, but I think you were already dealing with that.

> *ps. 18 year old bug? better late, then never ;)*

Oh yeah. It's not the first time that we're fixing such an old bug in ScummVM, though. The project was started in 2001 (by very talented people), but the tooling has improved since then, so our SCUMM implementation is getting more and more accurate. That's a really motivating thing.

And precise bug reports like yours help a lot. Thanks again.

**Comment by gabberhead** [comment] 2024-07-16 07:10
I copy the line from the Fan translate fmtowns Version, and put it in the right Place of the amiga Version and replace the old one with that one. I Importet the file, and test the game A bit. It works like it should.
 the amiga Version and the DOS ega Version, have also Text censore in the game. The fan Translation of the fmtowns Version, corrected it and corrected also the New spelling in the german language. The original Versionsnummer of that games, have the older german spelling.
The german VGA Version, also get this treatment already. But not from me. I am doing it now only for the amiga and DOS ega Version. Ro decensore the game completly. And i did Some changes with the audiotracks in the fmtowns Version.

**Comment by dwatteau** [comment] 2024-07-16 07:13
Alright thanks, so what I have the time to work on your ScummVM Trac issue about the censorship of the German releases, I will ping you for the Amiga/EGA tests, as the only official German release I have is the DOS VGA one.

Thanks.

**Closed by dwatteau** 2024-07-16 07:13 UTC
Labels: bug, unsupported game
